Update CameraTraps Batch API to utilize Megadetector V5
zooniverse/CameraTraps pull request #14
Opened 2023-11-28 22:26 UTC by yuenmichelle1

**Changes**
- Update Dockerfile to base off of Pytorch (MD v5 utilizes YOLOV5 [for object detection and image classification] and Pytorch)
- create a pytorch_detector.py based on detection/pytorch_detector.py and https://github.com/agentmorris/MegaDetector/blob/main/detection/pytorch_detector.py

2023-11-29 20:33 UTC, yuenmichelle1 commented
@zwolf  Feel free to do a full review of PR if you want (most of the file changes are pulled from microsoft cameratraps main repo). What I really need a review on is the GH action that replaces the jenkinsfile. 
GH Action
https://github.com/zooniverse/CameraTraps/pull/14/files#diff-53c24665441c6f14455ff3980322a41913e7c3bc35572986213fe21b9167734d

JenkinsFile
https://github.com/zooniverse/CameraTraps/pull/14/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8

2023-12-04 19:06 UTC, zwolf requested changes
I agree: the build/push process can use the shared workflow, but the deploy template location doesn't match the assumption in the shared one and so it needs to be separate. Also, couple of those action versions can be updated.

One thing this PR does need is for the kubernetes template to reflect the location of the image you're pushing. I can't add a suggestion to an unchanged file but this line:

https://github.com/zooniverse/CameraTraps/blob/b3b6b62916970797587f44987d030566c321f223/api/batch_processing/api_core/kubernetes/deployment.tmpl#L19

needs to be:
`image: ghcr.io/zooniverse/camera-traps-api:__IMAGE_TAG__`

Finally, just a suggestion: for clarity's sake, maybe you should delete the [other stale deployment branches](https://github.com/zooniverse/CameraTraps/branches/stale) if they're not being used.

2023-12-04 19:06 UTC, zwolf commented on .github/workflows/deploy_app.yml
> +      uses: actions/checkout@v3.5.2
I updated to this version in the shared workflows, thanks for the reminder.
```suggestion
      uses: actions/checkout@v4.1.1
```

2023-12-04 19:06 UTC, zwolf commented on .github/workflows/deploy_app.yml
> +      uses: docker/login-action@v2
```suggestion
      uses: docker/login-action@v3
```

2023-12-04 19:26 UTC, merged